language: go

go:
  - 1.9
  - master

install:
  - go get github.com/aws/aws-lambda-go/lambda
  - go get github.com/aws/aws-sdk-go/aws
  - go get github.com/aws/aws-sdk-go/aws/awserr
  - go get github.com/aws/aws-sdk-go/aws/request
  - go get github.com/aws/aws-sdk-go/aws/session
  - go get github.com/aws/aws-sdk-go/service/cloudwatchlogs
  - go get github.com/aws/aws-sdk-go/service/s3

matrix:
  allow_failures:
    - go: master
  fast_finish: true

notifications:
  email: false

before_script:
  - GO_FILES=$(find . -iname '*.go' -type f)
  - go get github.com/golang/lint/golint
  - go get honnef.co/go/tools/cmd/megacheck
  - go get github.com/fzipp/gocyclo

script:
  - test -z $(gofmt -s -l $GO_FILES)
  - go vet ./...
  - golint -set_exit_status $(go list ./...)
  - megacheck ./...
  - gocyclo -over 10 $GO_FILES
